name: mhe_clean_assignment
description: mhe_ clean_assignment.
publish_to: none
version: 2.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  clean_framework: ^2.0.8
  clean_framework_router: ^0.4.1
  dio: ^5.0.2

dev_dependencies:
  clean_framework_test: ^0.4.3
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/